### ISSUE TITLE
Operator chars inside of string literals are being parsed as operators

### ISSUE THREAD

**Issue by rweads0520** [mindsung/json-fx#8]
e.g. "$.someArray:join(',')" throws an error:
Operator "," expects 2 operands, 0 given

**Comment by aceads0529** [comment]
FxLoader wasn't checking token tags when loading definitions. It gives operator definitions the highest precedence, so if an operator exists with a given symbol (e.g. `,`) it loads that definition before trying to find a definition based on token tag (e.g. `literal`).

Fixed by only checking for an operator definition on valid token tags (i.e. not literals).
